/**@file 2c.c
 * @brief Convert the Abstract Syntax Tree generated by mpc for the DBC file
 * into some C code which can encode/decode signals.
 * @copyright Richard James Howe (2018), SUBLEQ LTD (2025)
 * @license MIT
 *
 * This file is quite a mess, but that is not going to change, it is also
 * quite short and seems to do the job. A better solution would be to make a
 * template tool, or a macro processor, suited for the task of generating C
 * code. The entire program really should be written in a language like Perl or
 * Python, but I wanted to use the MPC library for something, so here we are. */

/* TODO: Add in version number and commit of `dbcc` to generated files, this
 * should really go for all generators */

#include "2c.h"
#include "util.h"
#include <assert.h>
#include <ctype.h>
#include <inttypes.h>
#include <stdarg.h>
#include <string.h>

#define MAX_NAME_LENGTH (512u)
#define CAN_OBJ_MESSAGE_UNION_FIELD "messages"

static bool string_in_list(char **items, size_t count, const char *value)
{
	assert(value);
	for (size_t i = 0; i < count; i++) {
		if (!strcmp(items[i], value))
			return true;
	}
	return false;
}

static void add_unique_string(char ***items, size_t *count, const char *value)
{
	assert(items);
	assert(count);
	assert(value);
	if (string_in_list(*items, *count, value))
		return;
	*items = reallocator(*items, sizeof(**items) * (*count + 1));
	(*items)[(*count)++] = (char *)value;
}

static char *basename_without_extension(const char *name)
{
	assert(name);
	char *base = duplicate(name);
	char *dot = strrchr(base, '.');
	if (dot)
		*dot = '\0';
	return base;
}

static char *sanitize_identifier(const char *name, int upper)
{
	assert(name);
	char *id = duplicate(name);
	const size_t len = strlen(id);
	if (!len)
		return id;
	if (!isalpha(id[0]) && id[0] != '_')
		id[0] = '_';
	for (size_t i = 0; i < len; i++) {
		if (!isalnum(id[i]) && id[i] != '_') {
			id[i] = '_';
			continue;
		}
		id[i] = upper ? toupper(id[i]) : tolower(id[i]);
	}
	return id;
}

static int format_identifier(char *dst, size_t dst_len, dbc2c_options_t *copts, const char *base)
{
	assert(dst);
	assert(dst_len);
	assert(copts);
	assert(base);
	if (copts->symbol_namespace) {
		const size_t ns_len = strlen(copts->symbol_namespace);
		if (!strncmp(base, copts->symbol_namespace, ns_len) && base[ns_len] == '_')
			return snprintf(dst, dst_len, "%s", base);
		return snprintf(dst, dst_len, "%s_%s", copts->symbol_namespace, base);
	}
	return snprintf(dst, dst_len, "%s", base);
}

static int format_macro_identifier(char *dst, size_t dst_len, dbc2c_options_t *copts, const char *base)
{
	assert(dst);
	assert(dst_len);
	assert(copts);
	assert(base);
	if (copts->macro_namespace) {
		const size_t ns_len = strlen(copts->macro_namespace);
		if (!strncmp(base, copts->macro_namespace, ns_len) && base[ns_len] == '_')
			return snprintf(dst, dst_len, "%s", base);
		return snprintf(dst, dst_len, "%s_%s", copts->macro_namespace, base);
	}
	return snprintf(dst, dst_len, "%s", base);
}

static uint32_t hash32_update_bytes(uint32_t hash, const void *data, size_t size)
{
	const unsigned char *bytes = data;
	for (size_t i = 0; i < size; i++) {
		hash ^= bytes[i];
		hash *= 16777619u;
	}
	return hash;
}

static uint32_t hash32_update_cstr(uint32_t hash, const char *s)
{
	assert(s);
	return hash32_update_bytes(hash, s, strlen(s));
}

static uint32_t hash32_update_format(uint32_t hash, const char *fmt, ...)
{
	assert(fmt);
	va_list ap;
	va_start(ap, fmt);
	va_list ap_copy;
	va_copy(ap_copy, ap);
	int needed = vsnprintf(NULL, 0, fmt, ap);
	va_end(ap);
	if (needed < 0)
		error("vsnprintf failed while computing node hash");
	char *buf = allocate((size_t)needed + 1);
	vsnprintf(buf, (size_t)needed + 1, fmt, ap_copy);
	va_end(ap_copy);
	hash = hash32_update_bytes(hash, buf, (size_t)needed);
	free(buf);
	return hash;
}

static bool node_matches_signal(const signal_t *sig, const char *node)
{
	assert(sig);
	assert(node);
	for (size_t i = 0; i < sig->ecu_count; i++) {
		if (!strcmp(sig->ecus[i], node))
			return true;
	}
	return false;
}

static bool node_matches_message_tx(const can_msg_t *msg, const char *node)
{
	assert(msg);
	assert(node);
	for (size_t i = 0; i < msg->ecu_count; i++) {
		if (!strcmp(msg->ecus[i], node))
			return true;
	}
	return false;
}

static bool node_matches_message(const can_msg_t *msg, const char *node)
{
	assert(msg);
	assert(node);
	if (node_matches_message_tx(msg, node))
		return true;
	for (size_t i = 0; i < msg->signal_count; i++) {
		if (node_matches_signal(msg->sigs[i], node))
			return true;
	}
	return false;
}

static uint32_t hash_val_list(uint32_t hash, const val_list_t *val_list)
{
	if (!val_list)
		return hash32_update_cstr(hash, "VAL:none\n");

	hash = hash32_update_format(hash, "VAL:%s:%u:%d:",
		val_list->name ? val_list->name : "",
		val_list->id,
		(int)val_list->is_val_table_reference);
	if (val_list->val_table_name)
		hash = hash32_update_format(hash, "table=%s:", val_list->val_table_name);
	for (size_t i = 0; i < val_list->val_list_item_count; i++) {
		val_list_item_t *item = val_list->val_list_items[i];
		hash = hash32_update_format(hash, "%u=%s;", item->value, item->name);
	}
	return hash32_update_cstr(hash, "\n");
}

static uint32_t hash_mul_ranges(uint32_t hash, const signal_t *sig)
{
	assert(sig);
	hash = hash32_update_format(hash, "MUX:%d:%d:%u:%zu:",
		(int)sig->is_multiplexor,
		(int)sig->is_multiplexed,
		sig->switchval,
		sig->mul_num);
	if (sig->mux_parent)
		hash = hash32_update_format(hash, "parent=%s:", sig->mux_parent->name);
	for (size_t i = 0; i < sig->mul_num; i++) {
		mul_val_list_t *mv = sig->mux_vals[i];
		hash = hash32_update_format(hash, "%s:", sig->muxed[i]->name);
		if (mv) {
			hash = hash32_update_format(hash, "%s:%s:",
				mv->multiplexed ? mv->multiplexed : "",
				mv->multiplexor ? mv->multiplexor : "");
			for (size_t j = 0; j < mv->range_num; j++)
				hash = hash32_update_format(hash, "%u-%u,",
					mv->ranges[j]->min_value, mv->ranges[j]->max_value);
		}
		hash = hash32_update_cstr(hash, ";");
	}
	return hash32_update_cstr(hash, "\n");
}

static uint32_t hash_signal(uint32_t hash, const signal_t *sig)
{
	assert(sig);
	hash = hash32_update_format(hash,
		"SIG:%s:%u:%u:%d:%d:%d:%u:%.17g:%.17g:%.17g:%.17g:%s:",
		sig->name,
		sig->start_bit,
		sig->bit_length,
		(int)sig->endianess,
		(int)sig->is_signed,
		(int)sig->is_floating,
		sig->sigval,
		sig->scaling,
		sig->offset,
		sig->minimum,
		sig->maximum,
		sig->units ? sig->units : "");
	for (size_t i = 0; i < sig->ecu_count; i++)
		hash = hash32_update_format(hash, "%s,", sig->ecus[i]);
	hash = hash32_update_cstr(hash, "\n");
	hash = hash_mul_ranges(hash, sig);
	hash = hash_val_list(hash, sig->val_list);
	hash = hash32_update_format(hash, "COMMENT:%s\n", sig->comment ? sig->comment : "");
	return hash;
}

static uint32_t hash_message(uint32_t hash, const can_msg_t *msg)
{
	assert(msg);
	hash = hash32_update_format(hash, "MSG:%s:%lu:%u:%d:",
		msg->name, msg->id, msg->dlc, (int)msg->is_extended);
	for (size_t i = 0; i < msg->ecu_count; i++)
		hash = hash32_update_format(hash, "%s,", msg->ecus[i]);
	hash = hash32_update_cstr(hash, "\n");
	hash = hash32_update_format(hash, "COMMENT:%s\n", msg->comment ? msg->comment : "");
	for (size_t i = 0; i < msg->signal_count; i++)
		hash = hash_signal(hash, msg->sigs[i]);
	return hash;
}

static uint32_t dbc_node_hash32(const dbc_t *dbc, const char *node)
{
	assert(dbc);
	assert(node);
	uint32_t hash = 2166136261u;
	hash = hash32_update_format(hash, "NODE:%s\n", node);
	for (size_t i = 0; i < dbc->message_count; i++) {
		can_msg_t *msg = dbc->messages[i];
		if (node_matches_message(msg, node))
			hash = hash_message(hash, msg);
	}
	return hash;
}

static uint32_t dbc_hash32(const dbc_t *dbc)
{
	assert(dbc);
	uint32_t hash = 2166136261u;
	hash = hash32_update_cstr(hash, "DBC\n");
	for (size_t i = 0; i < dbc->message_count; i++)
		hash = hash_message(hash, dbc->messages[i]);
	return hash;
}

static void node_name_to_macro(const char *node, char *out, size_t out_size)
{
	assert(node);
	assert(out);
	assert(out_size > 0);
	size_t j = 0;
	for (size_t i = 0; node[i] && j + 1 < out_size; i++) {
		unsigned char c = (unsigned char)node[i];
		out[j++] = isalnum(c) ? (char)toupper(c) : '_';
	}
	out[j] = '\0';
}

static int fprintf_mux_group_name(FILE *o, signal_t *sig)
{
	assert(o);
	assert(sig);
	if (sig->mux_parent)
		return fprintf(o, "muxxer_%s", sig->mux_parent->name);

	/* Fallback for inconsistent/malformed multiplex relationships */
	return fprintf(o, "muxxer_%u", sig->start_bit);
}

static int fprintf_signal_access(FILE *o, const char *indent, const char *obj_name, const char *msg_name, const signal_t *sig, const char *suffix)
{
	assert(o);
	assert(indent);
	assert(obj_name);
	assert(msg_name);
	assert(sig);
	assert(suffix);
	const bool direct = msg_name[0] == '\0';
	if (msg_name[0]) {
		if (fprintf(o, "%s%s->%s.%s", indent, obj_name, CAN_OBJ_MESSAGE_UNION_FIELD, msg_name) < 0)
			return -1;
	} else {
		if (fprintf(o, "%s%s->", indent, obj_name) < 0)
			return -1;
	}
	if (sig->is_multiplexed) {
		if (!direct)
			if (fputc('.', o) < 0)
				return -1;
		if (fprintf_mux_group_name(o, (signal_t*)sig) < 0)
			return -1;
	}
	if (direct && !sig->is_multiplexed)
		return fprintf(o, "%s%s", sig->name, suffix);
	return fprintf(o, ".%s%s", sig->name, suffix);
}

static unsigned fix_start_bit(bool motorola, unsigned start, unsigned siglen)
{
	if (motorola)
		start = (8 * (7 - (start / 8))) + (start % 8) - (siglen - 1);
	return start;
}

static const char *determine_unsigned_type(unsigned length)
{
	const char *type = "uint64_t";
	if (length <= 32)
		type = "uint32_t";
	if (length <= 16)
		type = "uint16_t";
	if (length <= 8)
		type = "uint8_t";
	return type;
}

static const char *determine_signed_type(unsigned length)
{
	const char *type = "int64_t";
	if (length <= 32)
		type = "int32_t";
	if (length <= 16)
		type = "int16_t";
	if (length <= 8)
		type = "int8_t";
	return type;
}

static const char *determine_type(unsigned length, bool is_signed, bool is_floating)
{
	if (is_floating)
		return length == 64 ? "double" : "float";
	return is_signed ?
		determine_signed_type(length) :
		determine_unsigned_type(length);
}

static int signal2print(signal_t *sig, unsigned id, const char *obj_name, const char *msg_name, FILE *o)
{
	UNUSED(id);
	/*super lazy*/
	if (fprintf(o, "\tr = print_helper(r, fprintf(output, \"%s = (wire: %s)\\n\", (double)(",
			sig->name, sig->is_floating ? "%g" : "%.0f") < 0)
		return -1;
	if (fprintf_signal_access(o, "", obj_name, msg_name, sig, "") < 0)
		return -1;
	return fprintf(o, ")));\n");
}

static bool signal_are_min_max_valid(signal_t *sig)
{
	assert(sig);
	return sig->minimum != sig->maximum;
}

static uint64_t unsigned_max(signal_t *sig)
{
	assert(sig);
	if (sig->bit_length == 64)
		return UINT64_MAX;
	return (1uLL << (sig->bit_length)) - 1uLL;
}

static int64_t signed_max(signal_t *sig)
{
	assert(sig);
	if (sig->bit_length == 64)
		return INT64_MAX;
	return ((1uLL << (sig->bit_length - 1)) - 1uLL);
}

static int64_t signed_min(signal_t *sig)
{
	assert(sig);
	if (sig->bit_length == 64)
		return INT64_MIN;
	return ~signed_max(sig);
}

static const char *signal_api_type(const char *msgname, signal_t *sig, dbc2c_options_t *copts, char *buf, size_t buflen)
{
	assert(msgname);
	assert(sig);
	assert(copts);
	assert(buf);
	assert(buflen);
	const char *type = determine_type(sig->bit_length, sig->is_signed, sig->is_floating);
	if (copts->use_doubles_for_encoding || sig->scaling != 1.0 || sig->offset != 0.0)
		return "double";
	if (sig->is_floating || !sig->val_list || sig->val_list->val_list_item_count == 0)
		return type;

	if (sig->val_list->is_val_table_reference && sig->val_list->val_table_name) {
		char base[MAX_NAME_LENGTH] = { 0 };
		snprintf(base, sizeof(base), "val_table_%s_e", sig->val_list->val_table_name);
		format_identifier(buf, buflen, copts, base);
		return buf;
	}
	snprintf(buf, buflen, "%s_%s_e", msgname, sig->val_list->name);
	return buf;
}

static int fprintf_msg_obj_type(FILE *o, const char *msgname)
{
	assert(o);
	assert(msgname);
	return fprintf(o, "%s_obj_t", msgname);
}

static uint64_t signal_bit_mask(unsigned bit_length)
{
	return bit_length == 64 ? 0xFFFFFFFFFFFFFFFFuLL : ((1uLL << bit_length) - 1uLL);
}

static signal_t *signal_mux_parent(can_msg_t *msg, signal_t *sig)
{
	assert(msg);
	assert(sig);
	if (sig->mux_parent)
		return sig->mux_parent;
	if (!sig->is_multiplexed)
		return NULL;

	signal_t *fallback = NULL;
	for (size_t i = 0; i < msg->signal_count; i++) {
		signal_t *candidate = msg->sigs[i];
		if (!candidate->is_multiplexor)
			continue;
		if (!fallback)
			fallback = candidate;
		for (size_t j = 0; j < candidate->mul_num; j++)
			if (candidate->muxed[j] == sig)
				return candidate;
	}
	return fallback;
}

static int emit_extract_raw(FILE *o, signal_t *sig, const char *payload_expr, const char *var_name, const char *prefix, const char *indent)
{
	assert(o);
	assert(sig);
	assert(payload_expr);
	assert(var_name);
	assert(prefix);
	assert(indent);
	const bool motorola = (sig->endianess == endianess_motorola_e);
	const unsigned start = fix_start_bit(motorola, sig->start_bit, sig->bit_length);
	const uint64_t mask = signal_bit_mask(sig->bit_length);

	if (fprintf(o, "%suint64_t _payload_%s = (uint64_t)(%s);\n", indent, prefix, payload_expr) < 0)
		return -1;
	if (motorola) {
		if (fprintf(o, "%suint64_t _lane_%s = reverse_byte_order(_payload_%s);\n", indent, prefix, prefix) < 0)
			return -1;
	} else {
		if (fprintf(o, "%suint64_t _lane_%s = _payload_%s;\n", indent, prefix, prefix) < 0)
			return -1;
	}
	if (start)
		return fprintf(o, "%suint64_t %s = (_lane_%s >> %u) & 0x%" PRIx64 "uLL;\n", indent, var_name, prefix, start, mask);
	return fprintf(o, "%suint64_t %s = _lane_%s & 0x%" PRIx64 "uLL;\n", indent, var_name, prefix, mask);
}

static int emit_multiplex_check(can_msg_t *msg, signal_t *sig, FILE *o, const char *payload_expr, const char *indent, bool generate_asserts)
{
	assert(msg);
	assert(sig);
	assert(o);
	assert(payload_expr);
	assert(indent);
	if (!sig->is_multiplexed)
		return 0;

	signal_t *parent = signal_mux_parent(msg, sig);
	if (!parent)
		return 0;

	if (emit_extract_raw(o, parent, payload_expr, "_muxv", "mux", indent) < 0)
		return -1;

	bool have_range = false;
	if (!generate_asserts)
		return 0;
	if (fprintf(o, "%sassert((", indent) < 0)
		return -1;
	for (size_t i = 0; i < parent->mul_num; i++) {
		if (parent->muxed[i] != sig)
			continue;
		mul_val_list_t *mv = parent->mux_vals[i];
		if (!mv)
			continue;
		for (size_t r = 0; r < mv->range_num; r++) {
			if (have_range && fprintf(o, " || ") < 0)
				return -1;
			if (fprintf(o, "((_muxv >= %u) && (_muxv <= %u))",
				mv->ranges[r]->min_value,
				mv->ranges[r]->max_value) < 0)
				return -1;
			have_range = true;
		}
	}
	if (!have_range) {
		if (fprintf(o, "(_muxv == %u)", sig->switchval) < 0)
			return -1;
	}
	if (fprintf(o, "));\n") < 0)
		return -1;
	return 0;
}

static int emit_encode_value_to_x(FILE *o, signal_t *sig, uint64_t mask)
{
	assert(o);
	assert(sig);
	const bool needs_wire = sig->is_floating || sig->offset != 0.0 || sig->scaling != 1.0;

	if (needs_wire) {
		const char *wire_type = sig->is_floating ? determine_type(sig->bit_length, false, true) : "double";
		if (fprintf(o, "\t%s wire = (%s)in;\n", wire_type, wire_type) < 0)
			return -1;
		if (sig->offset != 0.0)
			if (fprintf(o, "\twire += %g;\n", -1.0 * sig->offset) < 0)
				return -1;
		if (sig->scaling != 1.0)
			if (fprintf(o, "\twire *= %g;\n", 1.0 / sig->scaling) < 0)
				return -1;
	}

	if (sig->is_floating) {
		assert(sig->bit_length == 32 || sig->bit_length == 64);
		if (sig->bit_length == 32) {
			if (fprintf(o, "\tuint32_t raw;\n") < 0)
				return -1;
			if (fprintf(o, "\tmemcpy(&raw, &wire, sizeof(raw));\n") < 0)
				return -1;
			return fprintf(o, "\tuint64_t x = ((uint64_t)raw) & 0x%" PRIx64 "uLL;\n", mask) < 0 ? -1 : 0;
		}
		if (fprintf(o, "\tuint64_t raw;\n") < 0)
			return -1;
		if (fprintf(o, "\tmemcpy(&raw, &wire, sizeof(raw));\n") < 0)
			return -1;
		return fprintf(o, "\tuint64_t x = raw & 0x%" PRIx64 "uLL;\n", mask) < 0 ? -1 : 0;
	}

	if (sig->is_signed) {
		if (needs_wire)
			return fprintf(o, "\tuint64_t x = ((uint64_t)((int64_t)wire)) & 0x%" PRIx64 "uLL;\n", mask) < 0 ? -1 : 0;
		return fprintf(o, "\tuint64_t x = ((uint64_t)((int64_t)in)) & 0x%" PRIx64 "uLL;\n", mask) < 0 ? -1 : 0;
	}

	if (needs_wire)
		return fprintf(o, "\tuint64_t x = ((uint64_t)wire) & 0x%" PRIx64 "uLL;\n", mask) < 0 ? -1 : 0;
	return fprintf(o, "\tuint64_t x = ((uint64_t)in) & 0x%" PRIx64 "uLL;\n", mask) < 0 ? -1 : 0;
}

static int emit_encode_payload_store(FILE *o, bool motorola, unsigned start, uint64_t mask)
{
	assert(o);
	if (motorola) {
		if (fprintf(o, "\tuint64_t lane = reverse_byte_order((uint64_t)o->payload);\n") < 0)
			return -1;
		if (start) {
			if (fprintf(o, "\tlane = (lane & ~(0x%" PRIx64 "uLL << %u)) | ((x & 0x%" PRIx64 "uLL) << %u);\n",
				mask, start, mask, start) < 0)
				return -1;
		} else {
			if (fprintf(o, "\tlane = (lane & ~0x%" PRIx64 "uLL) | (x & 0x%" PRIx64 "uLL);\n", mask, mask) < 0)
				return -1;
		}
		return fprintf(o, "\to->payload = reverse_byte_order(lane);\n") < 0 ? -1 : 0;
	}

	if (start)
		return fprintf(o, "\to->payload = (((uint64_t)o->payload) & ~(0x%" PRIx64 "uLL << %u)) | ((x & 0x%" PRIx64 "uLL) << %u);\n",
			mask, start, mask, start) < 0 ? -1 : 0;
	return fprintf(o, "\to->payload = (((uint64_t)o->payload) & ~0x%" PRIx64 "uLL) | (x & 0x%" PRIx64 "uLL);\n",
		mask, mask) < 0 ? -1 : 0;
}

static int signal2scaling_encode(can_msg_t *msg, const char *msgname, unsigned id, signal_t *sig, FILE *o, bool header, const char *god, dbc2c_options_t *copts)
{
	assert(msg);
	assert(msgname);
	assert(sig);
	assert(o);
	assert(copts);
	char api_type_buf[MAX_NAME_LENGTH] = { 0 };
	char function_name[MAX_NAME_LENGTH] = { 0 };
	char function_base[MAX_NAME_LENGTH] = { 0 };
	const char *type = signal_api_type(msgname, sig, copts, api_type_buf, sizeof api_type_buf);
	(void)god;
	if (copts->use_id_in_name)
		snprintf(function_base, sizeof(function_base), "encode_can_0x%03x_%s", id, sig->name);
	else if (copts->version >= 2)
		snprintf(function_base, sizeof(function_base), "encode_%s_%s", msgname, sig->name);
	else
		snprintf(function_base, sizeof(function_base), "encode_can_%s", sig->name);
	format_identifier(function_name, sizeof(function_name), copts, function_base);
	fprintf(o, "void %s(", function_name);
	if (fprintf_msg_obj_type(o, msgname) < 0)
		return -1;
	fprintf(o, " *o, %s in)", type);

	if (header)
		return fputs(";\n", o);
	fputs(" {\n", o);
	if (copts->generate_asserts) {
		fputs("\tassert(o);\n", o);
	}
	if (emit_multiplex_check(msg, sig, o, "o->payload", "\t", copts->generate_asserts) < 0)
		return -1;
	if (signal_are_min_max_valid(sig)) {
		bool gmax = true;
		bool gmin = true;

		if (sig->is_signed) {
			gmin = sig->minimum > signed_min(sig);
			gmax = sig->maximum < signed_max(sig);
		} else {
			gmin = sig->minimum > 0.0;
			gmax = sig->maximum < unsigned_max(sig);
		}
		if (sig->is_floating) {
			gmin = true;
			gmax = true;
		}

		if (gmin)
			fprintf(o, "\tassert(in >= %g);\n", sig->minimum);
		if (gmax)
			fprintf(o, "\tassert(in <= %g);\n", sig->maximum);
	}

	if (sig->scaling == 0.0)
		error("invalid scaling factor (fix your DBC file)");
	const bool motorola = (sig->endianess == endianess_motorola_e);
	const unsigned start = fix_start_bit(motorola, sig->start_bit, sig->bit_length);
	const uint64_t mask = signal_bit_mask(sig->bit_length);
	if (emit_encode_value_to_x(o, sig, mask) < 0)
		return -1;
	if (emit_encode_payload_store(o, motorola, start, mask) < 0)
		return -1;
	return fputs("\treturn;\n}\n\n", o);
}

static int signal2scaling_decode(can_msg_t *msg, const char *msgname, unsigned id, signal_t *sig, FILE *o, bool header, const char *god, dbc2c_options_t *copts)
{
	assert(msg);
	assert(msgname);
	assert(sig);
	assert(o);
	assert(copts);
	(void)god;
	char api_type_buf[MAX_NAME_LENGTH] = { 0 };
	char function_name[MAX_NAME_LENGTH] = { 0 };
	char function_base[MAX_NAME_LENGTH] = { 0 };
	const char *type = signal_api_type(msgname, sig, copts, api_type_buf, sizeof api_type_buf);
	if (copts->use_id_in_name)
		snprintf(function_base, sizeof(function_base), "decode_can_0x%03x_%s", id, sig->name);
	else if (copts->version >= 2)
		snprintf(function_base, sizeof(function_base), "decode_%s_%s", msgname, sig->name);
	else
		snprintf(function_base, sizeof(function_base), "decode_can_%s", sig->name);
	format_identifier(function_name, sizeof(function_name), copts, function_base);
	fprintf(o, "void %s(", function_name);
	if (fprintf_msg_obj_type(o, msgname) < 0)
		return -1;
	fprintf(o, " *o, %s *out)", type);
	if (header)
		return fputs(";\n", o);
	fputs(" {\n", o);
	if (copts->generate_asserts) {
		fputs("\tassert(o);\n", o);
		fputs("\tassert(out);\n", o);
	}
	if (emit_multiplex_check(msg, sig, o, "o->payload", "\t", copts->generate_asserts) < 0)
		return -1;
	if (emit_extract_raw(o, sig, "o->payload", "x", "sig", "\t") < 0)
		return -1;
	if (sig->is_floating) {
		assert(sig->bit_length == 32 || sig->bit_length == 64);
		if (sig->bit_length == 32) {
			fprintf(o, "\tuint32_t raw = (uint32_t)x;\n");
			fprintf(o, "\tfloat unpacked;\n");
			fprintf(o, "\tmemcpy(&unpacked, &raw, sizeof(unpacked));\n");
			fprintf(o, "\t%s rval = (%s)unpacked;\n", type, type);
		} else {
			fprintf(o, "\tuint64_t raw = (uint64_t)x;\n");
			fprintf(o, "\tdouble unpacked;\n");
			fprintf(o, "\tmemcpy(&unpacked, &raw, sizeof(unpacked));\n");
			fprintf(o, "\t%s rval = (%s)unpacked;\n", type, type);
		}
	} else if (sig->is_signed) {
		const uint64_t mask = signal_bit_mask(sig->bit_length);
		const uint64_t top = (1uLL << (sig->bit_length - 1));
		fprintf(o, "\tif ((x & 0x%" PRIx64 "uLL) != 0uLL)\n", top);
		fprintf(o, "\t\tx |= ~0x%" PRIx64 "uLL;\n", mask);
		fprintf(o, "\t%s rval = (%s)((int64_t)x);\n", type, type);
	} else {
		fprintf(o, "\t%s rval = (%s)x;\n", type, type);
	}
	if (sig->scaling == 0.0)
		error("invalid scaling factor (fix your DBC file)");
	if (sig->scaling != 1.0)
		fprintf(o, "\trval *= %g;\n", sig->scaling);
	if (sig->offset != 0.0)
		fprintf(o, "\trval += %g;\n", sig->offset);
	if (signal_are_min_max_valid(sig)) {
		bool gmax = true;
		bool gmin = true;

		if (sig->is_signed) { /**@warning comparison may fail because of limits of double size */
			gmin = sig->minimum > signed_min(sig);
			gmax = sig->maximum < signed_max(sig);
		} else {
			gmin = sig->minimum > 0.0;
			gmax = sig->maximum < unsigned_max(sig);
		}
		if (sig->is_floating) {
			gmin = true;
			gmax = true;
		}

		if (copts->generate_asserts) {
			if (gmin)
				fprintf(o, "\tassert(rval >= %g);\n", sig->minimum);
			if (gmax)
				fprintf(o, "\tassert(rval <= %g);\n", sig->maximum);
		}
	}
	fputs("\t*out = rval;\n", o);
	fputs("\treturn;\n", o);
	return fputs("}\n\n", o);
}

static int signal2scaling(can_msg_t *msg, const char *msgname, unsigned id, signal_t *sig, FILE *o, bool decode, bool header, const char *god, dbc2c_options_t *copts)
{
	assert(msg);
	assert(copts);
	if (decode)
		return signal2scaling_decode(msg, msgname, id, sig, o, header, god, copts);
	return signal2scaling_encode(msg, msgname, id, sig, o, header, god, copts);
}

static void make_name(char *newname, size_t maxlen, const char *name, unsigned id, dbc2c_options_t *copts)
{
	assert(newname);
	assert(name);
	assert(copts);
	char base[MAX_NAME_LENGTH] = { 0 };
	if (copts->use_id_in_name)
		snprintf(base, sizeof(base), "can_0x%03x_%s", id, name);
	else
		snprintf(base, sizeof(base), "can_%s", name);
	format_identifier(newname, maxlen, copts, base);
}

static signal_t *find_multiplexor(can_msg_t *msg) {
	assert(msg);
	signal_t *multiplexor = NULL;
	for (size_t i = 0; i < msg->signal_count; i++) {
		signal_t *sig = msg->sigs[i];
		if (sig->is_multiplexor) {
			multiplexor = sig;
		}
		if (sig->is_multiplexed)
			continue;
	}
	return multiplexor;
}

static int msg_print(can_msg_t *msg, FILE *c, const char *name, const char *god, dbc2c_options_t *copts)
{
	assert(msg);
	assert(c);
	assert(name);
	UNUSED(god);
	assert(copts);
	char print_name[MAX_NAME_LENGTH] = { 0 };
	format_identifier(print_name, sizeof(print_name), copts, name);
	fprintf(c, "int %s(const %s_t *o, FILE *output) {\n", print_name, name);
	if (copts->generate_asserts) {
		fputs("\tassert(o);\n", c);
		fputs("\tassert(output);\n", c);
		/* you may note the UNUSED macro may be generated, we should
		 * still assert we are passed the correct things */
	}
	if (msg->signal_count)
		fprintf(c, "\tint r = 0;\n");
	else
		fprintf(c, "\t(void)output;\n");
	for (size_t i = 0; i < msg->signal_count; i++) {
		if (signal2print(msg->sigs[i], msg->id, "o", "", c) < 0)
			return -1;
	}
	return msg->signal_count ? fprintf(c, "\treturn r;\n}\n\n") : fprintf(c, "\treturn 0;\n}\n\n");
}

static int msg_dlc_check(can_msg_t *msg) {
	assert(msg);
	const unsigned bits = msg->dlc * 8;
	unsigned used = 0;
	if (find_multiplexor(msg)) // skip multiplexed messages for now
		return 0;
	for (size_t i = 0; i < msg->signal_count; i++) {
		signal_t *s = msg->sigs[i];
		used += s->bit_length;
	}
	if (used > bits) {
		warning("Too many signals, not enough bytes (DLC is too low, fix your DBC file): %s", msg->name);
		return -1;
	}
	return 0;
}

static int msg2c(can_msg_t *msg, FILE *c, dbc2c_options_t *copts, char *god)
{
	assert(msg);
	assert(c);
	assert(copts);
	assert(god);
	char name[MAX_NAME_LENGTH] = {0};
	make_name(name, MAX_NAME_LENGTH, msg->name, msg->id, copts);
	bool motorola_used = false;
	bool intel_used = false;

	for (size_t i = 0; i < msg->signal_count; i++)
		if (msg->sigs[i]->endianess == endianess_motorola_e)
			motorola_used = true;
		else
			intel_used = true;

	/* sanity checks against messages should go here, we could check for;
	 * - odd min/max values given scaling
	 * - duplicate signals and messages
	 * They really should go into a semantic analysis phase after reading
	 * in the DBC file and parsing it. Oh Well. */
	msg_dlc_check(msg);

	/* Legacy pack/unpack generation intentionally disabled: signal APIs now operate directly on raw payload. */
	(void)motorola_used;
	(void)intel_used;

	for (size_t i = 0; i < msg->signal_count; i++) {
			if (copts->generate_unpack)
				if (signal2scaling(msg, name, msg->id, msg->sigs[i], c, true, false, god, copts) < 0)
					return -1;
			if (copts->generate_pack)
				if (signal2scaling(msg, name, msg->id, msg->sigs[i], c, false, false, god, copts) < 0)
					return -1;
	}

	if (copts->generate_print && msg_print(msg, c, name, god, copts) < 0)
		return -1;

	return 0;
}

static int msg2h(can_msg_t *msg, FILE *h, dbc2c_options_t *copts, const char *god)
{
	assert(msg);
	assert(h);
	assert(copts);
	assert(god);
	char name[MAX_NAME_LENGTH] = {0};
	make_name(name, MAX_NAME_LENGTH, msg->name, msg->id, copts);

	for (size_t i = 0; i < msg->signal_count; i++) {
		if (copts->generate_unpack)
			if (signal2scaling(msg, name, msg->id, msg->sigs[i], h, true, true, god, copts) < 0)
				return -1;
		if (copts->generate_pack)
			if (signal2scaling(msg, name, msg->id, msg->sigs[i], h, false, true, god, copts) < 0)
				return -1;
	}
	fputs("\n\n", h);
	return 0;
}

static const char *cfunctions =
"static inline uint64_t reverse_byte_order(uint64_t x) {\n"
"\tx = (x & 0x00000000FFFFFFFF) << 32 | (x & 0xFFFFFFFF00000000) >> 32;\n"
"\tx = (x & 0x0000FFFF0000FFFF) << 16 | (x & 0xFFFF0000FFFF0000) >> 16;\n"
"\tx = (x & 0x00FF00FF00FF00FF) << 8  | (x & 0xFF00FF00FF00FF00) >> 8;\n"
"\treturn x;\n"
"}\n\n";
static const char *cfunctions_print_only =
"static inline int print_helper(int r, int print_return_value) {\n"
"\treturn ((r >= 0) && (print_return_value >= 0)) ? r + print_return_value : -1;\n"
"}\n\n";

static int message_compare_function(const void *a, const void *b)
{
	assert(a);
	assert(b);
	can_msg_t *ap = *((can_msg_t**)a);
	can_msg_t *bp = *((can_msg_t**)b);
	if (ap->id <  bp->id) return -1;
	if (ap->id == bp->id) return  0;
	if (ap->id >  bp->id) return  1;
	return 0;
}

static int signal_compare_function(const void *a, const void *b)
{
	assert(a);
	assert(b);
	signal_t *ap = *((signal_t**)a);
	signal_t *bp = *((signal_t**)b);
	if (ap->bit_length <  bp->bit_length) return  1;
	if (ap->bit_length == bp->bit_length) return  0;
	if (ap->bit_length >  bp->bit_length) return -1;
	return 0;
}

static void normalize_multiplexed_flags(can_msg_t *msg)
{
	assert(msg);

	for (size_t i = 0; i < msg->signal_count; i++) {
		signal_t *sig = msg->sigs[i];
		for (size_t j = 0; j < sig->mul_num; j++)
			sig->muxed[j]->is_multiplexed = true;
	}
}

// TODO: Define enums as well/instead of.
/* NB. We should really use these enum names instead of the msg->id */
static void msg2h_define_can_ids(dbc_t *dbc, FILE *h, dbc2c_options_t *copts) {
	assert(dbc);
	assert(h);
	assert(copts);

	if (dbc->message_count == 0)
		return;

	const int ens = copts->generate_enum_can_ids;

	if (ens) {
		fprintf(h, "enum {\n"); // TODO: Typedef
	}
	for (size_t i = 0; i < dbc->message_count; i++) {
		can_msg_t *msg = dbc->messages[i];
		char *name = duplicate(msg->name);
		char macro_name[MAX_NAME_LENGTH] = { 0 };
		char macro_base[MAX_NAME_LENGTH] = { 0 };
		char dlc_macro_name[MAX_NAME_LENGTH] = { 0 };
		char dlc_macro_base[MAX_NAME_LENGTH] = { 0 };

		for (size_t i = 0; name[i] != 0; i++)
			name[i] = toupper(name[i]);
		snprintf(macro_base, sizeof(macro_base), "CAN_ID_%s", name);
		snprintf(dlc_macro_base, sizeof(dlc_macro_base), "CAN_DLC_%s", name);
		format_macro_identifier(macro_name, sizeof(macro_name), copts, macro_base);
		format_macro_identifier(dlc_macro_name, sizeof(dlc_macro_name), copts, dlc_macro_base);
		if (ens) {
			fprintf(h, "\t%s = %lu, /* 0x%lx */\n", macro_name, msg->id, msg->id);
		} else {
			fprintf(h, "#define %s (%lu) /* 0x%lx */\n", macro_name, msg->id, msg->id);
		}
		fprintf(h, "#define %s (%u)\n", dlc_macro_name, msg->dlc);

		free(name);
	}
	if (ens) {
		fprintf(h, "};\n");
	}

	fprintf(h, "\n");
}

static int msg2h_message_dlc_switch(dbc_t *dbc, FILE *h, dbc2c_options_t *copts)
{
	assert(dbc);
	assert(h);
	assert(copts);

	if (fprintf(h, "static inline int message_dlc_can2(const unsigned long id) {\n") < 0)
		return -1;
	if (fprintf(h, "\tswitch (id) {\n") < 0)
		return -1;

	for (size_t i = 0; i < dbc->message_count; i++) {
		can_msg_t *msg = dbc->messages[i];
		char *name = duplicate(msg->name);
		char id_macro_name[MAX_NAME_LENGTH] = { 0 };
		char id_macro_base[MAX_NAME_LENGTH] = { 0 };
		char dlc_macro_name[MAX_NAME_LENGTH] = { 0 };
		char dlc_macro_base[MAX_NAME_LENGTH] = { 0 };

		for (size_t j = 0; name[j] != 0; j++)
			name[j] = toupper(name[j]);
		snprintf(id_macro_base, sizeof(id_macro_base), "CAN_ID_%s", name);
		snprintf(dlc_macro_base, sizeof(dlc_macro_base), "CAN_DLC_%s", name);
		format_macro_identifier(id_macro_name, sizeof(id_macro_name), copts, id_macro_base);
		format_macro_identifier(dlc_macro_name, sizeof(dlc_macro_name), copts, dlc_macro_base);
		if (fprintf(h, "\tcase %s: return %s;\n", id_macro_name, dlc_macro_name) < 0) {
			free(name);
			return -1;
		}

		free(name);
	}

	if (fprintf(h,
		"\tdefault: return -1;\n"
		"\t}\n"
		"}\n\n") < 0)
		return -1;

	return 0;
}

static char *escape_string(const char *s, int upper) {
	const size_t max_char_len = 4;
	const size_t l = strlen(s) * max_char_len + 1;
	char *n = allocate(l);
	int ch = 0;
	for (size_t i = 0, j = 0; (ch = s[i]); i++) {
		assert(j < l);
		ch = ch == ' ' ? '_' : ch;
		if (!isalnum(ch) && ch != '_') {

			sprintf(&n[j], "_%02x_", ch);
			j += max_char_len;
		} else {
			if (upper > 0)
				ch = toupper(ch);
			if (upper < 0)
				ch = tolower(ch);
			n[j++] = ch;
		}
	}
	return n;
}

static int val_list2h_enum(FILE *h, const char *prefix, val_list_t *list, dbc2c_options_t *copts)
{
	assert(h);
	assert(list);
	assert(copts);

	if (list->val_list_item_count == 0)
		return 0;

	/* We really should use enum values in generated C codes/as types */
	fprintf(h, "typedef enum {\n");
	for (size_t j = 0; j < list->val_list_item_count; j++) {
		val_list_item_t *item = list->val_list_items[j];
		int r = 0;

		if (copts->version >= 2) {
			char *ename = escape_string(item->name, 0);
			if (strlen(ename) != strlen(item->name))
				warning("Non C-Ident characters in enumeration generation: '%s' -> '%s'", item->name, ename);
			char enum_value_name[MAX_NAME_LENGTH] = { 0, };
			char enum_value_base[MAX_NAME_LENGTH] = { 0, };
			if (prefix)
				r = snprintf(enum_value_base, MAX_NAME_LENGTH-1, "%s_%s_%s", prefix, list->name, ename);
			else
				r = snprintf(enum_value_base, MAX_NAME_LENGTH-1, "val_table_%s_%s", list->name, ename);
			if (prefix)
				snprintf(enum_value_name, sizeof(enum_value_name), "%s", enum_value_base);
			else
				format_identifier(enum_value_name, sizeof(enum_value_name), copts, enum_value_base);
			for (int i = 0; enum_value_name[i]; i++)
				enum_value_name[i] = toupper(enum_value_name[i]);
			fprintf(h, "\t%s = %u,\n", enum_value_name, item->value);
			free(ename);
		} else {
			char enum_value_name[MAX_NAME_LENGTH] = { 0, };
			char enum_value_base[MAX_NAME_LENGTH] = { 0, };
			snprintf(enum_value_base, sizeof(enum_value_base), "%s_%s_e", list->name, item->name);
			if (prefix)
				snprintf(enum_value_name, sizeof(enum_value_name), "%s", enum_value_base);
			else
				format_identifier(enum_value_name, sizeof(enum_value_name), copts, enum_value_base);
			r = fprintf(h, "\t%s = %u,\n", enum_value_name, item->value);
		}
		if (r < 0)
			error("output failed");
	}

	if (copts->version >= 2) {
		char enum_type_name[MAX_NAME_LENGTH] = { 0, };
		char enum_type_base[MAX_NAME_LENGTH] = { 0, };
		if (prefix)
			snprintf(enum_type_base, sizeof(enum_type_base), "%s_%s_e", prefix, list->name);
		else
			snprintf(enum_type_base, sizeof(enum_type_base), "val_table_%s_e", list->name);
		if (prefix)
			snprintf(enum_type_name, sizeof(enum_type_name), "%s", enum_type_base);
		else
			format_identifier(enum_type_name, sizeof(enum_type_name), copts, enum_type_base);
		fprintf(h, "} %s;\n\n", enum_type_name);
	} else {
		char enum_type_name[MAX_NAME_LENGTH] = { 0, };
		char enum_type_base[MAX_NAME_LENGTH] = { 0, };
		snprintf(enum_type_base, sizeof(enum_type_base), "%s_e", list->name);
		if (prefix)
			snprintf(enum_type_name, sizeof(enum_type_name), "%s", enum_type_base);
		else
			format_identifier(enum_type_name, sizeof(enum_type_name), copts, enum_type_base);
		fprintf(h, "} %s;\n\n", enum_type_name);
	}

	return 0;
}

static int val_tables2h_types(dbc_t *dbc, FILE *h, dbc2c_options_t *copts)
{
	assert(h);
	assert(dbc);
	assert(copts);

	for (size_t i = 0; i < dbc->val_table_count; i++)
		if (val_list2h_enum(h, NULL, dbc->val_tables[i], copts) < 0)
			return -1;

	return 0;
}

static int msg2h_types(dbc_t *dbc, FILE *h, dbc2c_options_t *copts)
{
	assert(h);
	assert(dbc);
	assert(copts);

	for (size_t i = 0; i < dbc->message_count; i++) {
		can_msg_t *msg = dbc->messages[i];
		char name[MAX_NAME_LENGTH] = {0};
		make_name(name, MAX_NAME_LENGTH, msg->name, msg->id, copts);

		for (size_t i = 0; i < msg->signal_count; i++) {
			signal_t* signal = msg->sigs[i];
			val_list_t *list = signal->val_list;

			if (!list)
				continue;
			if (list->is_val_table_reference)
				continue;

			if (val_list2h_enum(h, name, list, copts) < 0)
				return -1;
		}
	}

	return 0;
}

static int msg2h_objects(dbc_t *dbc, FILE *h, dbc2c_options_t *copts)
{
	assert(dbc);
	assert(h);
	assert(copts);
	for (size_t i = 0; i < dbc->message_count; i++) {
		can_msg_t *msg = dbc->messages[i];
		char name[MAX_NAME_LENGTH] = {0};
		make_name(name, MAX_NAME_LENGTH, msg->name, msg->id, copts);
		fprintf(h, "typedef struct {\n");
		fprintf(h, "\tuint64_t payload;\n");
		fprintf(h, "} %s_obj_t;\n", name);
		fprintf(h, "\n");
	}
	return 0;
}

static int msg2h_hashes(dbc_t *dbc, FILE *h, dbc2c_options_t *copts)
{
	assert(dbc);
	assert(h);
	assert(copts);

	char **nodes = NULL;
	size_t node_count = 0;
	for (size_t i = 0; i < dbc->message_count; i++) {
		can_msg_t *msg = dbc->messages[i];
		for (size_t j = 0; j < msg->ecu_count; j++)
			add_unique_string(&nodes, &node_count, msg->ecus[j]);
		for (size_t j = 0; j < msg->signal_count; j++) {
			signal_t *sig = msg->sigs[j];
			for (size_t k = 0; k < sig->ecu_count; k++)
				add_unique_string(&nodes, &node_count, sig->ecus[k]);
		}
	}

	char macro[MAX_NAME_LENGTH] = {0};
	format_macro_identifier(macro, sizeof(macro), copts, "DBCC_HASH");
	fprintf(h, "#define %s (0x%08" PRIx32 "u)\n", macro, dbc_hash32(dbc));
	for (size_t i = 0; i < node_count; i++) {
		char node_macro[MAX_NAME_LENGTH] = {0};
		char base_macro[MAX_NAME_LENGTH] = {0};
		node_name_to_macro(nodes[i], node_macro, sizeof(node_macro));
		snprintf(base_macro, sizeof(base_macro), "DBCC_NODE_HASH_%s", node_macro);
		format_macro_identifier(node_macro, sizeof(node_macro), copts, base_macro);
		fprintf(h, "#define %s (0x%08" PRIx32 "u)\n",
			node_macro, dbc_node_hash32(dbc, nodes[i]));
	}
	fputc('\n', h);
	free(nodes);
	return 0;
}

static int msg2c_objects(dbc_t *dbc, FILE *c, dbc2c_options_t *copts)
{
	assert(dbc);
	assert(c);
	assert(copts);
	for (size_t i = 0; i < dbc->message_count; i++) {
		can_msg_t *msg = dbc->messages[i];
		char name[MAX_NAME_LENGTH] = {0};
		make_name(name, MAX_NAME_LENGTH, msg->name, msg->id, copts);
		(void)msg;
		(void)name;
	}
	return 0;
}

static int msg2c_types(dbc_t *dbc, FILE *c, dbc2c_options_t *copts)
{
	assert(dbc);
	assert(c);
	assert(copts);
	(void)dbc;
	(void)c;
	(void)copts;
	return 0;
}

static char *msg2h_god_object(dbc_t *dbc, FILE *h, const char *name, dbc2c_options_t *copts)
{
	assert(h);
	assert(dbc);
	assert(copts);
	char *object_name = duplicate(name);
	const size_t object_name_len = strlen(object_name);
	for (size_t i = 0; i < object_name_len; i++)
		object_name[i] = (isalnum(object_name[i])) ?  tolower(object_name[i]) : '_';
	return object_name;
}

int dbc2c(dbc_t *dbc, FILE *c, FILE *h, const char *name, dbc2c_options_t *copts)
{
	assert(dbc);
	assert(c);
	assert(h);
	assert(name);
	assert(copts);
	int rv = 0;
	char *god = NULL;
	char *file_guard = duplicate(name);
	char *symbol_namespace = NULL;
	char *macro_namespace = NULL;
	char generator_version_macro[MAX_NAME_LENGTH] = { 0 };
	const size_t file_guard_len = strlen(file_guard);

	if (copts->namespace_from_filename) {
		char *base_name = basename_without_extension(name);
		symbol_namespace = sanitize_identifier(base_name, 0);
		macro_namespace = sanitize_identifier(base_name, 1);
		copts->symbol_namespace = symbol_namespace;
		copts->macro_namespace = macro_namespace;
		free(base_name);
	}
	format_macro_identifier(generator_version_macro, sizeof(generator_version_macro), copts, "DBCC_GENERATOR_VERSION");

	/* make file guard all upper case alphanumeric only, first character
	 * alpha only*/
	if (!isalpha(file_guard[0]))
		file_guard[0] = '_';
	for (size_t i = 0; i < file_guard_len; i++)
		file_guard[i] = (isalnum(file_guard[i])) ?  toupper(file_guard[i]) : '_';

	/* header file (begin) */
	fprintf(h, "/* CAN message encoder/decoder: automatically generated - do not edit.\n\n");

	if (fprintf(h,
		"This file was generated by dbcc: See <https://github.com/howerj/dbcc>\n\n"
		"For the professional version of this utility visit https://subleq.co.uk\n"
		"The professional version includes support for CAN-FD, more languages, and\n"
		"better MISRA-C support.\n"
		"\n\n*/\n\n"
		"#ifndef %s\n"
		"#define %s\n\n"
		"/* If the contents of this file have caused breaking changes for you, you could try using\n"
		"   an older version of the generator. You can specify this on the command line with\n"
		"   the -n option. */\n"
		"#define %s (%d)\n\n"
		"#include <stdint.h>\n"
		"%s\n\n"
		"#ifdef __cplusplus\n"
		"extern \"C\" { \n"
		"#endif\n\n",
		file_guard,
		file_guard,
		generator_version_macro,
		copts->version,
		copts->generate_print   ? "#include <stdio.h>"  : "") < 0)
			return -1;

	god = msg2h_god_object(dbc, h, name, copts);
	if (!god) {
		rv = -1;
		goto fail;
	}

	if (msg2h_hashes(dbc, h, copts) < 0) {
		rv = -1;
		goto fail;
	}

	/* sort signals by id */
	qsort(dbc->messages, dbc->message_count, sizeof(dbc->messages[0]), message_compare_function);

	/* sort by size for better struct packing */
	for (size_t i = 0; i < dbc->message_count; i++) {
		can_msg_t *msg = dbc->messages[i];
		normalize_multiplexed_flags(msg);
		qsort(msg->sigs, msg->signal_count, sizeof(msg->sigs[0]), signal_compare_function);
	}

	msg2h_define_can_ids(dbc, h, copts);
	if (msg2h_message_dlc_switch(dbc, h, copts) < 0) {
		rv = -1;
		goto fail;
	}

	if (val_tables2h_types(dbc, h, copts) < 0) {
		rv = -1;
		goto fail;
	}

	if (msg2h_types(dbc, h, copts) < 0) {
		rv = -1;
		goto fail;
	}
	if (msg2h_objects(dbc, h, copts) < 0) {
		rv = -1;
		goto fail;
	}

	fputs("\n", h);

	for (size_t i = 0; i < dbc->message_count; i++)
		if (msg2h(dbc->messages[i], h, copts, god) < 0)
			return -1;

	fputs(
		"#ifdef __cplusplus\n"
		"} \n"
		"#endif\n\n"
		"#endif\n",
		h);
	/* header file (end) */

	/* C FILE */
	const char *cput =
		"/* Generated by DBCC, see <https://github.com/howerj/dbcc>\n\n"
		"This file was generated by dbcc: See <https://github.com/howerj/dbcc>\n\n"
		"For the professional version of this utility visit https://subleq.co.uk\n"
		"The professional version includes support for CAN-FD, more languages, and\n"
		"better MISRA-C support.\n"
		"\n\n*/\n\n";

	if (fputs(cput, c) < 0) return -1;

	if (fprintf(c, "#include \"%s\"\n", name) < 0) return -1;
	if (fprintf(c, "#include <inttypes.h>\n") < 0) return -1;
	if (fprintf(c, "#include <string.h>\n") < 0) return -1;
	if (copts->generate_asserts)
		fprintf(c, "#include <assert.h>\n");
	fputc('\n', c);
	if (msg2c_types(dbc, c, copts) < 0) {
		rv = -1;
		goto fail;
	}
	if (msg2c_objects(dbc, c, copts) < 0) {
		rv = -1;
		goto fail;
	}
	fputs(cfunctions, c);
	if (copts->generate_print)
		fputs(cfunctions_print_only, c);

	for (size_t i = 0; i < dbc->message_count; i++)
		if (msg2c(dbc->messages[i], c, copts, god) < 0) {
			rv = -1;
			goto fail;
		}

fail:
	copts->symbol_namespace = NULL;
	copts->macro_namespace = NULL;
	free(symbol_namespace);
	free(macro_namespace);
	free(file_guard);
	free(god);
	return rv;
}
