name: Check Secret

on:
  push:
    branches: [test_action]

jobs:
  check-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Check if secret is set
        run: |
          if [ -z "${{ secrets.CI_ACCESS_TOKEN_SECRET }}" ]; then
            echo "❌ Secret CI_ACCESS_TOKEN_SECRET is NOT set or not accessible"
            exit 1
          else
            echo "✅ Secret CI_ACCESS_TOKEN_SECRET is set"
          fi